name: Deploy to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Deploy to Railway
        uses: railway-org/railway-action@v1
        with:
          service: your-app-name
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
